#Ingresar 10 valores por teclado y obtener la sumatoria de los mismos. Imprimir los resultados.

val1 = int(input("Ingresar val1"))
val2 = int(input("Ingresar val2"))
val3 = int(input("Ingresar val3"))
val4 = int(input("Ingresar val4"))
val5 = int(input("Ingresar val5"))
val6 = int(input("Ingresar val6"))
val7 = int(input("Ingresar val7"))
val8 = int(input("Ingresar val8"))
val9 = int(input("Ingresar val9"))
val10 = int(input("Ingresar val10"))

suma_mismos = (val1 + val2 + val3 + val4 + val5 + val6 + val7 + val8 + val9 + val10)
print ("Resultados es igual a :", suma_mismos)
