#Ingresar 10 valores numéricos por teclado y calcular la suma, el promedio e imprimir la suma, el promedio agregando una leyenda en cada caso.

num1 = int(input("Ingresar num1"))
num2 = int(input("Ingresar num2"))
num3 = int(input("Ingresar num3"))
num4 = int(input("Ingresar num4"))
num5 = int(input("Ingresar num5"))
num6 = int(input("Ingresar num6"))
num7 = int(input("Ingresar num7"))
num8 = int(input("Ingresar num8"))
num9 = int(input("Ingresar num9"))
num10 = int(input("Ingresar num10"))

suma_num = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10)
    print("La suma total es:", suma_num)
prom_num = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10)/10
    print(" El promedio es:", prom_num)
